site_name: selfx-oss
site_url: https:selfx.ai4cps.com
repo_url: https://github.com/ai4cps-com/selfx-oss
repo_name: ai4cps-com/selfx-oss

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Installation: installation.md
  - API: api.md

markdown_extensions:
  - admonition
  - fenced_code
  - tables
  - toc:
      permalink: true